### ISSUE TITLE
Set step number as data-attribute on element, for dynamic css content

### ISSUE THREAD

**Issue by nathanallen** [HeyHeyTaeTae/Spiffify#4]
Here's a neat way we can refactor `.steps1`, `.steps2`, `.steps3` to just be `.step`. Note that the only difference between them is that you had to manually set `content: "1"`, `content: "2"`, `content: "3"`.

First, add a `data` attribute to each of your "steps" like so:
``` html
<div class="col-xs-6 steps1 how-steps" data-step="1">
    ...
</div>
```

Then, in your css, tell it to use `data-step` to set the content:

``` css
.steps1::before {
	content: data(step);       /* No more hardcoding! */
        ...
}
```

Finally, refactor your css rule to just be `.step` and make the corresponding change in your html. Voila!
